name: Develop

# 全てのブランチでpushされたら実行
on:
  push:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: slack-archives-opener
        path: |
          .
          !*.md
          !.git*
          !.github*
          !screen          